---
# Parking Monitor Component Configuration
# AI-powered parking space detection and monitoring service

parking_monitor_component:
  # Service configuration
  ansible.builtin.service:
    name: "com.orangead.parking-monitor"
    port: "{{ service_ports.parking_monitor }}"
    bind_address: "127.0.0.1"
    python_version: "{{ python_version_lookup.parking_monitor }}"

  # Repository configuration
  repository:
    url: "https://github.com/oa-device/oaParkingMonitor.git"
    branch: "main"
    destination: "{{ ansible_user_dir }}/orangead/parking-monitor"

  # Detection configuration (conservative defaults)
  detection:
    model: "yolo11m"
    confidence_threshold: 0.5
    target_fps: 30.000030  # Precise framerate for macOS USB cameras
    device: "mps" # Apple Silicon optimization
    debug_mode: false
    save_detection_images: false

  # Camera configuration
  camera:
    source: 0
    resolution: [1920, 1080]
    fps: 30.000030  # Precise framerate for macOS USB cameras
    debug_capture: false
    save_frames: false
    staging_mode: false

  # Health monitoring (production defaults)
  health_monitoring:
    enabled: true
    check_interval: 30
    performance_alerts: true
    debug_metrics: false
    save_metrics: false
    thresholds:
      min_fps: 25
      max_memory_gb: 4
      max_cpu_percent: 80
      min_accuracy: 0.9

  # Display configuration
  display:
    enabled: true
    overlay_enabled: true
    overlay_opacity: 0.7
    status_position: "top_right"
    show_vehicle_info: true
    show_debug_info: false
    show_fps: false
    show_model_info: false
    ad_integration: true

  # Environment-specific overrides
  environment_overrides:
    staging:
      detection:
        debug_mode: true
        save_detection_images: true
        confidence_threshold: 0.3
        model: "yolo11n" # Lighter model for staging
      camera:
        debug_capture: true
        save_frames: true
        staging_mode: true
      health_monitoring:
        debug_metrics: true
        save_metrics: true
        check_interval: 10
      display:
        show_debug_info: true
        show_fps: true
        show_model_info: true
        ad_integration: false

    preprod:
      detection:
        debug_mode: true
        confidence_threshold: 0.4
      health_monitoring:
        performance_alerts: false

    production:
      detection:
        confidence_threshold: 0.5
        debug_mode: false
      health_monitoring:
        performance_alerts: true
        check_interval: 30
