---
# macOS Platform Group Variables
# Platform-specific configuration for all macOS devices

# Platform identification
platform:
  name: "macos"
  type: "desktop"
  capabilities:
    - "gui"
    - "launchd"
    - "homebrew"
    - "camera"

# macOS-specific package management
system:
  package_manager: "homebrew"

# Service management
services:
  type: "launchd"
  user_agents_path: "{{ ansible_user_dir }}/Library/LaunchAgents"
  system_daemons_path: "/Library/LaunchDaemons"

# macOS-specific paths
paths:
  user_applications: "{{ ansible_user_dir }}/Applications"
  orangead_base: "{{ ansible_user_dir }}/orangead"
  logs_base: "{{ ansible_user_dir }}/orangead/logs"

# macOS platform-specific packages (always installed)
macos_platform_packages:
  - mas
  - mackup
  - rectangle

# Security settings
security:
  firewall:
    enabled: true
    allow_signed_app: true
  privacy:
    camera_permissions_required: true
    full_disk_access_required: false

# Network configuration
network:
  configure_wifi: false # Set to true to configure Wi-Fi networks from vault

# Tailscale configuration for all macOS devices
tailscale:
  enabled: true
  tags:
    - "tag:oa-macos"
    - "tag:oa-device"
