---
all:
  vars:
    target_env: evenko-camguard-all-prod
    project_name: evenko
    deployment_environment: production
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: ssh
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_ssh_pipelining: true
    ansible_become_method: sudo

    # Runtime versions
    python:
      version: "3.11.11"
    node:
      version: "22.11.0"

    # Feature toggles
    configure:
      tailscale: false # Production - Tailscale managed separately
      pyenv: true
      node: true

    # Environment-specific features (Production CamGuard deployment)
    oa_environment:
      name: "evenko-camguard-all-prod"
      project: "evenko"
      allow_experimental: false
      allow_server_optimizations: false # Conservative for production
      allow_destructive_operations: false
      # NEW REQUEST: Deploy camguard to ALL evenko machines
      deploy_device_api: true # Required for camguard monitoring
      deploy_tracker: false
      deploy_alpr_service: false
      deploy_player: false # Player already deployed separately
      deploy_camguard: true # NEW: Camera recording for all machines

    # Custom wallpaper deployment (disabled for camguard-only deployment)
    deploy_custom_wallpaper: false

    # System packages (minimal for production)
    system:
      homebrew:
        packages:
          - go
          - git
          - wget
          - jq
          - curl
          - lsd
          - ffmpeg # Required for camguard video recording

    # CamGuard configuration for ALL evenko machines
    camguard:
      enabled: true
      # Recording schedule - 7 days a week for comprehensive monitoring
      schedule_enabled: true
      recording_days: [0, 1, 2, 3, 4, 5, 6] # Sunday through Saturday
      start_time: "00:00"
      end_time: "23:59"
      # Video settings optimized for monitoring
      recording:
        resolution: "1920x1080"
        framerate: 30
        bitrate: "4M"
        segment_duration: 900 # 15 minutes per file
        format: "mp4"
        codec: "h264_videotoolbox" # Hardware acceleration
      # Storage settings
      storage:
        retention_days: 7 # Keep recordings for 1 week
        max_storage_gb: 150 # Limit storage per machine
        cleanup_enabled: true
        auto_cleanup_hour: 2 # Cleanup at 2 AM daily
      # RTSP streaming for live monitoring
      streaming:
        enabled: true
        port: 8554
        path: "/live"
      # Transfer settings (disabled by default)
      transfer:
        enabled: false
        remote_host: ""
        remote_path: ""
        cleanup_after_transfer: false

  children:
    macos:
      hosts:
        f1-ca-001:
          ansible_host: 100.103.229.95
          ansible_user: studio
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-001'] }}"
        f1-ca-002:
          ansible_host: 100.122.121.83
          ansible_user: ek003
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-002'] }}"
        f1-ca-003:
          ansible_host: 100.114.173.58
          ansible_user: ek002
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-003'] }}"
        f1-ca-005:
          ansible_host: 100.120.130.91
          ansible_user: ek000
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-005'] }}"
        f1-ca-007:
          ansible_host: 100.78.224.4
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-007'] }}"
        f1-ca-011:
          ansible_host: 100.108.127.23
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-011'] }}"
        f1-ca-012:
          ansible_host: 100.67.135.111
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-012'] }}"
        f1-ca-016:
          ansible_host: 100.68.254.108
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-016'] }}"
