---
all:
  vars:
    # Ansible connection configuration
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: ssh
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_ssh_pipelining: true
    ansible_become_method: sudo

    # Runtime versions (standardized structure)
    runtime:
      python:
        version: "3.11.11"
      node:
        version: "22.11.0"

    # Feature toggles
    configure:
      tailscale: false # Production - Tailscale managed separately
      uv_python: true
      node: true

    # Environment configuration (standardized single source of truth)
    oa_environment:
      name: "evenko-tracker-prod"
      project: "evenko"
      stage: "production"
      allow_experimental: false
      allow_server_optimizations: false # Conservative for production
      allow_destructive_operations: false
      # Evenko tracker project components: macos-api, tracker only (same as f1)
      deploy_device_api: true
      deploy_tracker: true
      deploy_alpr_service: false
      deploy_player: false

    # System packages (minimal for production)
    system:
      homebrew:
        packages:
          - go
          - git
          - wget
          - jq
          - curl
          - lsd

    # Tracker configuration
    tracker:
      repository_url: "https://github.com/oa-device/oaTracker.git"
      git_version: "main"
      default_yolo_source: 0
      default_model: "yolo12s.pt"
      server_port: 8080

  children:
    macos:
      hosts:
        f1-ca-013:
          ansible_host: 100.100.39.53
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-013'] }}"
          cam_id: "e1109807-d70b-4f79-ad2e-88b439903235"
        f1-ca-017:
          ansible_host: 100.83.231.37
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-017'] }}"
          cam_id: "979d9cc5-a8b4-45bb-a6cf-8d988ab2f1eb"
