---
# Simplified deployment check for unified Device API
# Since we're always forcing updates, this just gathers basic info

- name: Check if unified Device API directory exists
  ansible.builtin.stat:
    path: "{{ device_api_path }}/main.py"
  register: unified_api_deployed

- name: Display deployment approach
  ansible.builtin.debug:
    msg: |
      ===============================================
      Device API Deployment Approach
      ===============================================
      - Deployment Mode: FORCE UPDATE (Always)
      - API Currently Deployed: {{ unified_api_deployed.stat.exists }}
      - Target Path: {{ device_api_path }}
      - Service Name: {{ device_api_service_name }}
      - Strategy: Complete refresh of code, dependencies, and service
      ===============================================
      
      This deployment will:
      ✓ Force git update to latest {{ device_api.branch | default('main') }}
      ✓ Recreate Python virtual environment
      ✓ Reinstall all dependencies
      ✓ Stop and restart {{ device_api_service_name }} service
      ✓ Validate API endpoints are working
      ===============================================