---
# Simplified Handlers for parking monitor role - Device Setup Only
# These handlers manage the LaunchAgent service lifecycle

- name: restart parking monitor
  shell: |
    launchctl unload "{{ parking_monitor_launchd.plist_path }}" 2>/dev/null || true
    sleep 2
    launchctl load "{{ parking_monitor_launchd.plist_path }}"
  become: false
  listen: "restart parking monitor"

- name: reload parking monitor
  shell: |
    launchctl kickstart -k "gui/{{ ansible_user_id }}/{{ parking_monitor_service.name }}"
  become: false
  listen: "reload parking monitor"

- name: stop parking monitor
  shell: |
    launchctl unload "{{ parking_monitor_launchd.plist_path }}" 2>/dev/null || true
  become: false
  listen: "stop parking monitor"

- name: start parking monitor  
  shell: |
    launchctl load "{{ parking_monitor_launchd.plist_path }}"
  become: false
  listen: "start parking monitor"

- name: validate parking monitor service
  uri:
    url: "http://localhost:9091/health"
    method: GET
    status_code: 200
    timeout: 30
  retries: 5
  delay: 10
  listen: "validate parking monitor service"

- name: refresh python environment
  shell: |
    cd "{{ parking_monitor_repository.destination }}"
    uv sync
  become: false
  listen: "refresh python environment"