---
# Ubuntu Python Environment Setup

- name: Configure UV and Python for Ubuntu
  import_role:
    name: common/uv_python
  vars:
    uv_python_version: "{{ ubuntu_python_version }}"
    uv_ubuntu_install_deps: true
    uv_ubuntu_dev_packages: "{{ ubuntu_dev_packages }}"

- name: Install system Python packages (compatibility)
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present
  become: true
  when: ubuntu_install_system_python
  tags: [python, packages]

- name: Display Python setup results
  ansible.builtin.debug:
    msg:
      - "[PYTHON] UV Python Environment Setup Complete"
      - "Python Version: {{ uv_python_version }}"
      - "UV Path: {{ uv_install_dir }}/uv"
      - "Python Command: uv run python"
      - "Development Packages: {{ 'Installed' if uv_ubuntu_install_deps else 'Skipped' }}"
  tags: [python, summary]
