---
# Enhanced Python Role with Improved Idempotency
# Uses state detection framework for efficient deployment

- name: Import state detection for Python environment
  ansible.builtin.include_tasks: ../../../tasks/state-detection.yml
  tags: ["always"]

- name: Configure UV and Python (Streamlined)
  when:
    - macos_configure.uv_python | default(macos_configure.pyenv) | bool
    - platform_state.is_macos
  import_role:
    name: common/uv_python
  vars:
    uv_python_version: "{{ python_state.target_version }}"

# Set completion facts for dependent roles
- name: Set Python environment completion facts
  ansible.builtin.set_fact:
    python_environment_ready: true
    python_version_installed: "{{ python_state.target_version }}"
    python_manager: "uv"
    uv_available: true
  tags: ["always"]
