---
# Encrypt this file with: ansible-vault encrypt group_vars/all/vault.yml

# Tailscale configuration
vault_tailscale_auth_key: "tskey-auth-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
vault_tailscale_api_key: "tskey-api-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
vault_tailscale_tailnet: "orangead.ca"
vault_tailscale_tags_macos: "tag:oa-macos,tag:oa-tracker"

# SSH keys - REQUIRED for all deployments
vault_ssh_private_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  # Your private key here
  -----END OPENSSH PRIVATE KEY-----
vault_ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2E... user@example.com"
# Host-specific sudo passwords - REQUIRED for each device
# Each device must have its password explicitly defined
vault_sudo_passwords:
  # F1 Project (device-api + tracker)
  f1-ca-001: "f1-device-password"
  f1-ca-002: "f1-device-password"
  f1-ca-003: "f1-device-password"
  f1-ca-004: "f1-device-password"
  f1-ca-005: "f1-device-password"
  f1-ca-007: "f1-device-password"
  f1-ca-009: "f1-device-password"
  f1-ca-011: "f1-device-password"
  f1-ca-012: "f1-device-password"
  f1-ca-013: "f1-device-password"
  f1-ca-014: "f1-device-password"
  f1-ca-015: "f1-device-password"
  f1-ca-016: "f1-device-password"
  f1-ca-017: "f1-device-password"

  # Spectra Project (device-api + tracker + video-player)
  spectra-staging-001: "spectra-device-password"
  spectra-staging-002: "spectra-device-password"
  spectra-preprod-001: "spectra-device-password"
  spectra-prod-001: "spectra-device-password"
  spectra-prod-002: "spectra-device-password"

  # ALPR Project (device-api + alpr)
  alpr-staging-001: "alpr-device-password"
  alpr-preprod-001: "alpr-device-password"
  alpr-prod-001: "alpr-device-password"

  # Legacy devices (to be migrated)
  kampus-rig: "legacy-password"
  kai-vm-001: "legacy-password"
  kai-vm-002: "legacy-password"
  m4-ca-001: "existing-device-password"

# Ubuntu server configuration (OPTIONAL - only for new Ubuntu servers)
vault_ubuntu_ansible_user: "admin"
vault_ubuntu_sudo_password: "ubuntu-server-sudo-password"

# Tracker secrets (for macOS tracking service)
vault_tracker_access_key: "tracker-access-key"
vault_tracker_secret_key: "tracker-secret-key"

# ALPR service secrets (optional)
vault_alpr_token: "platerecognizer-api-token"
vault_alpr_license_key: "platerecognizer-license-key"

# Wi-Fi configuration (for macOS devices)
vault_wifi_networks:
  - ssid: "Kampus"
    password: "Kampus94"
    security_type: "WPA2"
