---
# Detect Python installation from UV
- name: Get UV root directory
  ansible.builtin.shell: |
    echo $HOME/.local/bin
  register: macos_uv_root
  changed_when: false
  when:
    - configure.uv_python | default(true) # UV is now the default Python manager

- name: Set UV root fact
  ansible.builtin.set_fact:
    uv_root: "{{ macos_uv_root.stdout }}"
  when: macos_uv_root is defined and macos_uv_root.rc == 0

- name: Get Python executable path from UV
  ansible.builtin.shell: |
    set -o pipefail
    export PATH="{{ uv_root.stdout }}:$PATH"
    uv run python -c "import sys; print(sys.executable)"
  register: macos_uv_python_path
  changed_when: false
  failed_when: false
  when: uv_root is defined

- name: Set detected Python executable
  ansible.builtin.set_fact:
    macos_python_executable: "{{ macos_uv_python_path.stdout if macos_uv_python_path.rc == 0 else '/usr/bin/python3' }}"

- name: Debug Python path
  ansible.builtin.debug:
    msg: "Using Python executable: {{ python_executable }}"
