---
all:
  vars:
    # Environment and project identification
    target_env: "yuh-prod"
    deployment_environment: "production"
    oa_environment:
      name: "yuh-prod"
      stage: "production"

    # Project-specific configuration
    project_name: "yuh"
    project_type: "airport"
    location: "YUH Airport"
    
    # Parking Monitor Configuration (Primary Service)
    parking_monitor:
      enabled: true
      repository_url: "https://github.com/oa-device/oaParkingMonitor.git"
      branch: "main"
      port: 9091
      python_version: "3.12"
      
      # Detection Configuration
      detection:
        model: "yolo11m"
        confidence_threshold: 0.5
        target_fps: 30
        device: "mps"  # Mac M1 Metal Performance Shaders
        
      # Camera Configuration
      camera:
        source: 0  # Primary USB camera
        resolution: [1920, 1080]
        fps: 30
        
      # Parking Space Configuration (YUH-specific)
      parking_zones:
        total_spaces: 24
        zones:
          - name: "Terminal North"
            spaces: 12
            coordinates: "auto_detect"  # Will be configured during deployment
          - name: "Terminal South" 
            spaces: 12
            coordinates: "auto_detect"
            
      # Display Configuration
      display:
        enabled: true
        overlay_enabled: true
        overlay_opacity: 0.7
        status_position: "top_right"
        show_vehicle_info: true
        ad_integration: true
        
      # Health Monitoring
      health_monitoring:
        enabled: true
        check_interval: 30
        performance_alerts: true
        thresholds:
          min_fps: 25
          max_memory_gb: 4
          max_cpu_percent: 80
          min_accuracy: 0.9

    # Player configuration (Dual-screen: ads + parking overlay)
    player:
      enabled: true
      dual_screen: true
      loop_mode: true
      video_selection_strategy: "sequential"
      health_check: true
      restart_on_failure: true
      health_check_interval: 180
      restart_attempts: 3
      restart_delay: 15
      volume: 0.0
      
      # Integration with Parking Monitor
      parking_overlay: true
      overlay_transparency: 0.3
      
      # Kiosk mode settings
      fullscreen: true
      hide_cursor: true
      black_background: true
      disable_screensaver: true

    # Device API Configuration (for oaDashboard integration)
    device_api:
      enabled: true
      port: 9090
      python_version: "3.12"
      repository_url: "https://github.com/oa-device/oaDeviceAPI.git"
      branch: "main"
      
      # Platform-specific configuration
      platform_detection: true
      macos_features:
        - health_monitoring
        - parking_monitor_proxy
        - system_metrics
        - tracker_integration

    # Tailscale Configuration
    tailscale:
      enabled: true
      hostname_prefix: "yuh-airport"
      exit_node: false
      accept_routes: true
      advertise_exit_node: false
      
    # Security Configuration
    security:
      firewall_enabled: true
      allowed_ports:
        - 22     # SSH
        - 9090   # Device API
        - 9091   # Parking Monitor
        - 8080   # Player (if needed)
      
      # Camera permissions
      camera_permissions: true
      full_disk_access: true
      automation_permissions: true
      
    # Logging Configuration
    logging:
      enabled: true
      log_level: "INFO"
      max_log_size: "100MB"
      max_log_files: 5
      centralized_logging: true
      
    # System Optimization
    system_optimization:
      enabled: true
      power_management: "high_performance"
      disable_sleep: true
      auto_login: true
      reduce_transparency: true
      
    # Monitoring and Alerting
    monitoring:
      enabled: true
      metrics_collection: true
      health_checks: true
      alert_webhooks:
        - "{{ vault_slack_webhook_url }}"
      
      # Service monitoring
      services:
        - parking_monitor
        - player
        - device_api
        - tailscale

  children:
    yuh_airport:
      hosts:
        f1-ca-015:
          ansible_host: 100.91.66.122
          ansible_user: admin
          ansible_port: 22
          ansible_become_password: "{{ vault_sudo_passwords['f1-ca-015'] }}"
          hostname: "yuh-airport-001"
          device_role: "primary_parking_monitor"
          camera_id: 0
          display_id: 0
          parking_zone: "Terminal North"
          cam_id: "f5f9b8d0-6048-4cbb-8fb7-39df676733a0"