---
# Production Environment Configuration
# Remote environment with strict security and stability controls

environment:
  name: "production"
  type: "remote"
  description: "Production environment with maximum stability and security"

# Network access configuration (most restrictive)
network:
  access_type: "tailscale_only"  # Only accessible via Tailscale
  tailscale_management: false  # STRICTLY BANNED - production stability
  ssh_access: "tailscale"  # SSH only via Tailscale network

# Feature toggles (conservative for production)
features:
  tailscale_configuration: false  # STRICTLY BANNED
  debug_mode: false
  experimental_features: false
  destructive_operations: false
  server_optimizations: false  # Conservative for production stability

# Environment permissions (most restrictive)
permissions:
  allow_experimental: false
  allow_server_optimizations: false
  allow_destructive_operations: false
  allow_package_installation: false
  allow_service_restarts: true  # Only for maintenance
  allow_configuration_changes: false  # Minimal changes only

# Component-specific production overrides (optimized for stability)
component_overrides:
  device-api:
    debug_mode: false
    log_level: "WARNING"
    performance_monitoring: true
    
  parking-monitor:
    detection:
      debug_mode: false
      confidence_threshold: 0.5  # Balanced accuracy
      save_detection_images: false
    health_monitoring:
      performance_alerts: true
      check_interval: 30
    display:
      show_debug_info: false
      show_fps: false
      ad_integration: true
      
  player:
    fullscreen: true
    hide_cursor: true
    black_background: true
    disable_screensaver: true
    health_check_interval: 300  # Less frequent checks
    restart_attempts: 2  # Conservative restart policy
    
  tracker:
    default_model: "yolo12s.pt"  # Production model
    debug_mode: false
    
  camguard:
    debug_mode: false
    check_interval: 60
    alert_threshold: 10  # More conservative alerting

# Minimal packages for production (security focus)
additional_packages:
  macos:
    - go
    - git
    - wget
    - jq
    - curl
    - lsd
    
# Logging configuration (minimal but comprehensive)
logging:
  level: "WARNING"
  console_output: false
  file_output: true
  structured_logging: true
  max_log_files: 10
  max_log_size: "50MB"
  centralized_logging: true

# Monitoring configuration (production-grade)
monitoring:
  enabled: true
  debug_monitoring: false
  development_mode: false
  metrics_collection: true
  performance_alerts: true
  alert_webhooks: 
    - "{{ production_webhook_url | default('') }}"  # Configure in secrets

# Security configuration
security:
  firewall_enabled: true
  allowed_ports:
    - 22     # SSH
    - 9090   # Device API
    - 9091   # Parking Monitor (if deployed)
    - 8080   # Tracker (if deployed)
  camera_permissions: true
  full_disk_access: true
  automation_permissions: true