---
# Ubuntu Python Role Defaults
# Python environment setup for Ubuntu servers

# Python version management
ubuntu_python_version: "3.11"
ubuntu_install_pyenv: false  # Deprecated: Use UV instead
ubuntu_install_system_python: true

# Package managers
ubuntu_install_uv: true # Fast Python package manager
ubuntu_install_pip: true

# Development tools
ubuntu_install_dev_packages: true
ubuntu_dev_packages:
  - python3-dev
  - python3-pip
  - python3-venv
  - python3-setuptools
  - python3-wheel
  - build-essential
  - libssl-dev
  - libffi-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - libncursesw5-dev
  - libgdbm-dev
  - liblzma-dev
  - tk-dev
  - uuid-dev

# PyEnv configuration
ubuntu_pyenv_root: "{{ ansible_user_dir }}/.pyenv"  # Legacy - deprecated
ubuntu_pyenv_install_python_versions: []  # Deprecated: Use UV instead

# Virtual environment settings
ubuntu_create_default_venv: false # ML workstation role will handle this
ubuntu_default_venv_name: "ml-env"

# PATH configuration
ubuntu_update_shell_profile: true
ubuntu_shell_profiles:
  - "{{ ansible_user_dir }}/.bashrc"
  - "{{ ansible_user_dir }}/.zshrc"
