---
# Project Template - Preprod Hosts
# Define pre-production environment hosts for this project

all:
  vars:
    # Environment identification
    target_env: "yhu-preprod"
    deployment_environment: "preprod"

    # Project reference
    project_name: "yhu"

    # Component deployment (from stack.yml)
    components_to_deploy: "{{ project_stack.components }}"

    # Component configurations (from stack.yml + environment overrides)
    component_configurations: "{{ project_stack.component_configs | combine(
      project_stack.environment_overrides.preprod | default({}),
      recursive=True
    ) }}"

  children:
    "yhu_preprod":
      children:
        macos:
          hosts:
            # YHU Preprod Host - f1-ca-014 configured for parking monitoring
            "f1-ca-014":
              ansible_host: "100.74.169.36"  # TAILSCALE IP
              ansible_user: "admin"
              ansible_port: 22
              ansible_become_password: "{{ vault_sudo_passwords['f1-ca-014'] }}"
              
              # Host-specific configuration for YHU parking monitoring
              cam_id: "1ec0b062-a1e6-46b8-bfb0-9ab3ac45eb45"
              environment_type: "preprod"
              
              # YHU parking-specific configuration
              parking_zones:
                total_spaces: 8
                zone_coordinates:
                  # Default parking zone configuration - to be refined based on camera view
                  zone_1: [[100, 100], [300, 100], [300, 200], [100, 200]]
                  zone_2: [[400, 100], [600, 100], [600, 200], [400, 200]]
                  zone_3: [[100, 300], [300, 300], [300, 400], [100, 400]]
                  zone_4: [[400, 300], [600, 300], [600, 400], [400, 400]]
              
              # Camera configuration for parking lot monitoring  
              # Optimized for macOS USB cameras - precise framerate prevents camera configuration failures
              camera:
                source: 0
                resolution: "1920x1080"
                fps: 30.000030           # Precise framerate required for macOS USB cameras
                pixel_format: "uyvy422"  # Native camera format for better performance
                input_format: "avfoundation"
                codec: "h264_videotoolbox" # Hardware acceleration on macOS
                preset: "ultrafast"      # Low latency for real-time monitoring