---
# Project Template - Preprod Hosts
# Define pre-production environment hosts for this project

all:
  vars:
    # Environment identification
    target_env: "yhu-preprod"
    deployment_environment: "preprod"

    # Project reference
    project_name: "yhu"

    # Component deployment (from stack.yml)
    components_to_deploy: "{{ project_stack.components }}"

    # Component configurations (from stack.yml + environment overrides)
    component_configurations: "{{ project_stack.component_configs | combine(
      project_stack.environment_overrides.preprod | default({}),
      recursive=True
    ) }}"

  children:
    "yhu_preprod":
      children:
        macos:
          hosts:
            # YHU Preprod Host - f1-ca-014 configured for parking monitoring
            "f1-ca-014":
              ansible_host: "100.74.169.36"  # TAILSCALE IP
              ansible_user: "admin"
              ansible_port: 22
              ansible_become_password: "{{ vault_sudo_passwords['f1-ca-014'] }}"
              
              # Host-specific configuration for YHU parking monitoring
              cam_id: "1ec0b062-a1e6-46b8-bfb0-9ab3ac45eb45"
              environment_type: "preprod"
              
              # YHU MVP parking configuration - 11 zones
              parking_zones:
                total_spaces: 11
                zones:
                  # Front row zones (A-series)
                  - name: "A1"
                    coordinates: [[308, 306], [151, 296], [151, 561]]
                    space_id: 1
                    description: "Front left space (partially visible)"
                    detection_difficulty: "hard"
                  - name: "A2"
                    coordinates: [[511, 320], [320, 308], [153, 576], [384, 611]]
                    space_id: 2
                    description: "Front row center-left"
                    detection_difficulty: "easy"
                  - name: "A3"
                    coordinates: [[711, 328], [520, 320], [392, 612], [625, 633]]
                    space_id: 3
                    description: "Front row center"
                    detection_difficulty: "easy"
                  - name: "A4"
                    coordinates: [[914, 335], [719, 328], [630, 633], [867, 652]]
                    space_id: 4
                    description: "Front row center-right"
                    detection_difficulty: "easy"
                  - name: "A5"
                    coordinates: [[1132, 344], [922, 337], [874, 654], [1117, 669]]
                    space_id: 5
                    description: "Front row right-center"
                    detection_difficulty: "easy"
                  - name: "A6"
                    coordinates: [[1354, 354], [1135, 339], [1129, 667], [1383, 674]]
                    space_id: 6
                    description: "Front row right"
                    detection_difficulty: "easy"
                  - name: "A7"
                    coordinates: [[1588, 365], [1361, 349], [1388, 678], [1677, 690]]
                    space_id: 7
                    description: "Front row far right"
                    detection_difficulty: "easy"
                  # Back row zones (B-series)
                  - name: "B1"
                    coordinates: [[998, 0], [982, 48], [1142, 65], [1166, 0]]
                    space_id: 8
                    description: "Back row left"
                    detection_difficulty: "hard"
                  - name: "B2"
                    coordinates: [[1170, 0], [1151, 64], [1325, 81], [1338, 0]]
                    space_id: 9
                    description: "Back row center-left"
                    detection_difficulty: "hard"
                  - name: "B3"
                    coordinates: [[1349, 0], [1330, 84], [1516, 100], [1514, 0]]
                    space_id: 10
                    description: "Back row center-right"
                    detection_difficulty: "hard"
                  - name: "B4"
                    coordinates: [[1523, 3], [1519, 101], [1712, 100], [1689, 5]]
                    space_id: 11
                    description: "Back row right"
                    detection_difficulty: "hard"
              
              # Camera configuration for parking lot monitoring  
              # Optimized for macOS USB cameras - precise framerate prevents camera configuration failures
              camera:
                source: 0
                resolution: "1920x1080"
                fps: 30.000030           # Precise framerate required for macOS USB cameras
                pixel_format: "uyvy422"  # Native camera format for better performance
                input_format: "avfoundation"
                codec: "h264_videotoolbox" # Hardware acceleration on macOS
                preset: "ultrafast"      # Low latency for real-time monitoring