---
# Project Template - Preprod Hosts
# Define pre-production environment hosts for this project

all:
  vars:
    # Environment identification
    target_env: "yhu-preprod"
    deployment_environment: "preprod"

    # Project reference
    project_name: "yhu"

    # Component deployment (from stack.yml)
    components_to_deploy: "{{ project_stack.components }}"

    # Component configurations (from stack.yml + environment overrides)
    component_configurations: "{{ project_stack.component_configs | combine(
      project_stack.environment_overrides.preprod | default({}),
      recursive=True
    ) }}"

  children:
    "yhu_preprod":
      children:
        macos:
          hosts:
            # YHU Preprod Host - f1-ca-014 configured for parking monitoring
            "f1-ca-014":
              ansible_host: "100.74.169.36"  # TAILSCALE IP
              ansible_user: "admin"
              ansible_port: 22
              ansible_become_password: "{{ vault_sudo_passwords['f1-ca-014'] }}"
              
              # Host-specific configuration for YHU parking monitoring
              cam_id: "1ec0b062-a1e6-46b8-bfb0-9ab3ac45eb45"
              environment_type: "preprod"
              
              # YHU parking-specific configuration
              parking_zones:
                total_spaces: 6
                zones:
                  - name: "Zone1"
                    coordinates: [[332, 303], [153, 289], [5, 538], [212, 576]]
                    space_id: 1
                    description: "Parking space Zone1"
                  - name: "Zone2"  
                    coordinates: [[340, 297], [217, 573], [434, 581], [527, 300]]
                    space_id: 2
                    description: "Parking space Zone2"
                  - name: "Zone3"
                    coordinates: [[535, 311], [710, 316], [659, 594], [447, 589]]
                    space_id: 3
                    description: "Parking space Zone3"
                  - name: "Zone4"
                    coordinates: [[720, 316], [897, 332], [892, 621], [672, 602]]
                    space_id: 4
                    description: "Parking space Zone4"
                  - name: "Zone5"
                    coordinates: [[913, 332], [1114, 340], [1138, 627], [908, 621]]
                    space_id: 5
                    description: "Parking space Zone5"
                  - name: "Zone6"
                    coordinates: [[1125, 348], [1325, 353], [1395, 627], [1151, 629]]
                    space_id: 6
                    description: "Parking space Zone6"
              
              # Camera configuration for parking lot monitoring  
              # Optimized for macOS USB cameras - precise framerate prevents camera configuration failures
              camera:
                source: 0
                resolution: "1920x1080"
                fps: 30.000030           # Precise framerate required for macOS USB cameras
                pixel_format: "uyvy422"  # Native camera format for better performance
                input_format: "avfoundation"
                codec: "h264_videotoolbox" # Hardware acceleration on macOS
                preset: "ultrafast"      # Low latency for real-time monitoring