---
# Main tasks for staging video feed deployment
# This role provides virtual camera functionality for parking monitor testing

- name: Validate staging environment
  ansible.builtin.debug:
    msg:
      "Deploying staging video feed in {{ deployment_environment | default('unknown') }} environment with parking monitor {{ 'enabled' if
      parking_monitor.enabled | default(false) else 'disabled' }}"
  tags: [staging-video-feed, parking-monitor, validation]

- name: Include system dependencies setup
  ansible.builtin.include_tasks:
    file: system_setup.yml
    apply:
      tags: [staging-video-feed, parking-monitor, system]
  tags: [staging-video-feed, parking-monitor, system]

- name: Include video content management
  ansible.builtin.include_tasks:
    file: video_management.yml
    apply:
      tags: [staging-video-feed, parking-monitor, videos]
  tags: [staging-video-feed, parking-monitor, videos]

- name: Include virtual camera setup
  ansible.builtin.include_tasks:
    file: virtual_camera.yml
    apply:
      tags: [staging-video-feed, parking-monitor, camera]
  tags: [staging-video-feed, parking-monitor, camera]

- name: Include service configuration
  ansible.builtin.include_tasks:
    file: service_setup.yml
    apply:
      tags: [staging-video-feed, parking-monitor, service]
  tags: [staging-video-feed, parking-monitor, service]

- name: Include health verification
  ansible.builtin.include_tasks:
    file: health_verification.yml
    apply:
      tags: [staging-video-feed, parking-monitor, health]
  tags: [staging-video-feed, parking-monitor, health]

- name: Display staging video feed summary
  ansible.builtin.debug:
    msg: |
      ===============================================
      [CAMERA] Staging Video Feed Deployment Summary
      ===============================================
      Service: {{ staging_video_feed_service.name }}
      Virtual Device: {{ staging_video_feed_camera.device_path }}
      Video Storage: {{ staging_video_feed_content.storage_dir }}
      Working Directory: {{ staging_video_feed_service.working_dir }}
      ===============================================
      [OK] Staging Video Feed deployed successfully!

      Integration:
      - Parking monitor will use camera source: {{ staging_video_feed_integration.camera_device_override }}
      - Virtual camera device: {{ staging_video_feed_camera.device_path }}
      - Service coordinates with parking monitor startup

      Next steps:
      1. Service will auto-start before parking monitor
      2. Videos will be downloaded and cycled automatically
      3. Virtual camera will be available for parking monitor
      ===============================================
  tags: [staging-video-feed, parking-monitor, summary]
