---
# Service setup and configuration for staging video feed

- name: Create staging video feed service script
  ansible.builtin.template:
    src: staging_video_feed_service.py.j2
    dest: "{{ staging_video_feed_service.working_dir }}/staging_video_feed_service.py"
    mode: "0755"
    owner: "{{ staging_video_feed_service.user }}"
    group: "{{ staging_video_feed_service.group }}"
  become: false
  notify: restart staging video feed service

- name: Create service startup script
  ansible.builtin.template:
    src: start_service.sh.j2
    dest: "{{ staging_video_feed_service.working_dir }}/scripts/start_service.sh"
    mode: "0755"
    owner: "{{ staging_video_feed_service.user }}"
    group: "{{ staging_video_feed_service.group }}"
  become: false

- name: Create LaunchAgent plist for staging video feed
  ansible.builtin.template:
    src: com.orangead.staging-video-feed.plist.j2
    dest: "{{ staging_video_feed_launchd.plist_path }}"
    mode: "0644"
    owner: "{{ staging_video_feed_service.user }}"
    group: "{{ staging_video_feed_service.group }}"
  become: false
  notify: reload staging video feed service

- name: Stop existing staging video feed service
  ansible.builtin.command: launchctl unload {{ staging_video_feed_launchd.plist_path }}
  become: false
  failed_when: false
  changed_when: false

- name: Load staging video feed service
  ansible.builtin.command: launchctl load {{ staging_video_feed_launchd.plist_path }}
  become: false
  register: service_load_result

- name: Wait for service to initialize
  ansible.builtin.wait_for:
    timeout: 10
  when: service_load_result is succeeded

- name: Verify service is running
  ansible.builtin.command: launchctl list | grep com.orangead.staging-video-feed
  register: service_status
  failed_when: false
  changed_when: false
  become: false

- name: Display service status
  ansible.builtin.debug:
    msg: |
      Service Status:
      - Service name: {{ staging_video_feed_service.name }}
      - Plist path: {{ staging_video_feed_launchd.plist_path }}
      - Status: {{ 'Running' if service_status.rc == 0 else 'Not running' }}
      - Working directory: {{ staging_video_feed_service.working_dir }}
