---
# Simplified Parking Monitor Role - Device Setup Only
# Project-specific configurations moved to oaParkingMonitor/config/

# Repository Configuration (Device Setup)
parking_monitor_repository:
  url: "https://github.com/oa-device/oaParkingMonitor.git"
  branch: "main"
  destination: "{{ service_defaults.directories.base }}/parking-monitor"
  force_update: false

# Service Configuration (Device Setup)
parking_monitor_service:
  name: "{{ service_defaults.naming.prefix }}.parking-monitor"
  user: "{{ ansible_user }}"
  group: "staff"
  port: "{{ service_ports.parking_monitor }}"

# Python Environment Configuration (Device Setup)
parking_monitor_python:
  version: "{{ service_defaults.python.version }}"
  requirements_file: "{{ service_defaults.python.requirements_file }}"
  project_path: "{{ service_defaults.directories.base }}/parking-monitor"
  python_command: "{{ service_defaults.python.package_manager }} run python"

# LaunchAgent Configuration (Device Setup)
parking_monitor_launchd:
  plist_name: "{{ parking_monitor_service.name }}.plist"
  plist_path: "{{ ansible_user_dir }}/Library/LaunchAgents/{{ parking_monitor_service.name }}.plist"
  run_at_load: true
  keep_alive: true
  restart_on_failure: true
  throttle_interval: 10
  standard_out_path: "/tmp/parking-monitor.out"
  standard_error_path: "/tmp/parking-monitor.err"

# Environment Variables (Device Setup - Minimal Injection)
parking_monitor_environment:
  PARKING_MONITOR_ENV: "{{ target_env | default('staging') }}"
  PYTHONPATH: "{{ parking_monitor_repository.destination }}/src"
  LOG_LEVEL: "INFO"
  # Site-specific variables (injected from inventory)
  SITE_NAME: "{{ project_name | default('') }}"
  SITE_LOCATION: "{{ location | default('') }}"
  TARGET_ENV: "{{ target_env | default('staging') }}"
  DEVICE_ROLE: "{{ device_role | default('') }}"
  PARKING_ZONE: "{{ parking_zone | default('') }}"
  # Network configuration
  TAILSCALE_SUBNET: "{{ tailscale_subnet | default('100.64.0.0/10') }}"

# System Dependencies (Device Setup)
parking_monitor_dependencies:
  system_packages:
    - cmake
    - pkg-config
  # Python packages handled by project's uv setup

# Security Configuration (Device Setup)
parking_monitor_security:
  required_permissions:
    - camera_access
    - full_disk_access
    - automation_access
  firewall_rules: [] # Can be overridden in inventory if needed

# Models Configuration (Minimal for compatibility)
parking_monitor_models:
  model_dir: "{{ parking_monitor_repository.destination }}/models"
  auto_download: false # Handled by project itself

