---
# Unified Device API Component Configuration
# Settings for the unified oaDeviceAPI service deployment

component:
  name: "device-api"
  description: "FastAPI service for unified device management (macOS and OrangePi)"
  platforms: ["macos", "orangepi"]
  dependencies: ["python", "base"]
# Service configuration
ansible.builtin.service:
  name: "com.orangead.deviceapi"
  port: 9090
  bind_address: "127.0.0.1"
  workers: 1

# Deployment settings
deployment:
  path: "{{ ansible_user_dir }}/orangead/oaDeviceAPI"
  venv_path: "{{ ansible_user_dir }}/orangead/oaDeviceAPI/.venv"
  logs_path: "{{ ansible_user_dir }}/orangead/oaDeviceAPI/logs"
  config_path: "{{ ansible_user_dir }}/orangead/oaDeviceAPI/config"

# Python requirements
python:
  version: "{{ runtime.python.version }}"
  requirements_file: "requirements.txt"
  packages:
    - "fastapi"
    - "uvicorn"
    - "pydantic"
    - "psutil"
    - "opencv-python-headless"
    - "httpx"

# LaunchAgent configuration
launchd:
  plist_name: "com.orangead.deviceapi.plist"
  plist_path: "{{ ansible_user_dir }}/Library/LaunchAgents/com.orangead.deviceapi.plist"
  working_directory: "{{ ansible_user_dir }}/orangead/oaDeviceAPI"
  environment_variables:
    PYTHONPATH: "{{ ansible_user_dir }}/orangead/oaDeviceAPI/src"

# Health check configuration
health:
  endpoint: "/health"
  timeout: 30
  retries: 3

# Security settings
security:
  tailscale_subnet_middleware: true
  api_key_required: false
  allowed_hosts: ["localhost", "127.0.0.1"]
# Logging configuration
logging:
  level: "INFO"
  rotation: "1 week"
  retention: "4 weeks"
  max_size: "10MB"
