---
# Parking Monitor Component Configuration
# This file defines the parking monitor service component that can be deployed
# across different environments and projects

all:
  vars:
    # Component Identification
    component_name: "parking-monitor"
    component_type: "ai_detection_service"
    component_category: "monitoring"
    
    # Essential Service Configuration (Device Setup Only)
    parking_monitor_service_name: "com.orangead.parking-monitor"
    parking_monitor_user: "{{ ansible_user }}"
    parking_monitor_group: "staff"
    
    # Repository Configuration (Device Setup)
    parking_monitor_repository:
      url: "https://github.com/oa-device/oaParkingMonitor.git"
      branch: "main"  # Override per environment
      destination: "{{ ansible_user_dir }}/orangead/parking-monitor"
      
    # Python Environment (Device Setup)
    parking_monitor_python_version: "3.12"
    parking_monitor_python_env:
      path: "{{ ansible_user_dir }}/.pyenv/versions/{{ parking_monitor_python_version }}/envs/parking-monitor"
      
    # Service Management (macOS LaunchAgent)
    parking_monitor_launchd:
      plist_name: "{{ parking_monitor_service_name }}.plist"
      plist_path: "{{ ansible_user_dir }}/Library/LaunchAgents/{{ parking_monitor_launchd.plist_name }}"
      run_at_load: true
      keep_alive: true
      standard_out_path: "/tmp/parking-monitor.out"
      standard_error_path: "/tmp/parking-monitor.err"
      
    # Essential Dependencies (Device Setup)
    parking_monitor_dependencies:
      system_packages:
        - cmake
        - pkg-config
        
    # Security Configuration (Device Setup)
    parking_monitor_security:
      required_permissions:
        - camera_access
        - full_disk_access
        - automation_access
        
    # Integration Points (Device Setup)
    parking_monitor_integration:
      dashboard_endpoints:
        - path: "/health"
          purpose: "Health check for oaDashboard monitoring"
        - path: "/api/parking/status" 
          purpose: "Current parking occupancy data"
      
      service_discovery:
        advertise_port: 9091
        service_tags:
          - parking-monitor
          - ai-detection

# Simplified Compatibility Matrix
parking_monitor_compatibility:
  platforms:
    macos:
      min_version: "12.0"  # macOS Monterey for M1 support
      required_features:
        - metal_performance_shaders
        - coreml
        - camera_access
      
  # Essential service compatibility only
  services:
    device_api:
      compatible: true
      integration: "health_proxy"
      required: true