---
# macOS Tracker deployment
# Modular task orchestration for improved maintainability and idempotency

# System setup and prerequisites
- name: System setup and prerequisites
  ansible.builtin.include_tasks: system_setup.yml
  tags: ["tracker", "system", "setup"]

# Directory management
- name: Directory management and setup
  ansible.builtin.include_tasks: directory_mgmt.yml
  tags: ["tracker", "directory"]

# Git repository management (standardized)
- name: Repository setup (standardized git management)
  ansible.builtin.include_tasks: "{{ playbook_dir }}/../tasks/git-repository-management.yml"
  vars:
    repo_component_name: "tracker"
    repo_url: "{{ merged_tracker_config.repository_url }}"
    repo_branch: "{{ final_git_version }}"
    repo_destination: "{{ ansible_user_dir }}/orangead/tracker"
    repo_force_update: "{{ tracker_force_update | default(false) }}"
    repo_owner: "{{ ansible_user }}"
    repo_group: "staff"
  tags: ["tracker", "git", "repository"]

# Configuration validation (non-git tasks only)
- name: Configuration validation
  ansible.builtin.include_tasks: config_validation.yml
  tags: ["tracker", "config", "validation"]

# Python environment and dependencies
- name: Python environment setup
  ansible.builtin.include_tasks: python_setup.yml
  tags: ["tracker", "python", "dependencies"]

# Service configuration and LaunchAgent setup
- name: Service configuration and setup
  ansible.builtin.include_tasks: service_setup.yml
  tags: ["tracker", "service", "launchd"]

# Deployment verification and health checks
- name: Deployment verification
  ansible.builtin.include_tasks: verify_deployment.yml
  tags: ["tracker", "verify", "status"]
