---
# Configuration management tasks
# Creates and manages configuration files for the parking monitor service

# NOTE: oaParkingMonitor loads configuration from config/mvp.yaml (bundled with app)
# No external config.yaml needed - app has all defaults and environment overrides via .env

- name: Create environment configuration
  ansible.builtin.template:
    src: parking_monitor.env.j2
    dest: "{{ parking_monitor_repository.destination }}/.env"
    mode: "0600" # Sensitive environment variables
  notify: reload parking monitor

- name: Validate configuration syntax
  ansible.builtin.shell: |
    cd "{{ parking_monitor_repository.destination }}"
    if [ -f .venv/bin/python ]; then
      PYTHON_BIN=".venv/bin/python"
    else
      PYTHON_BIN="python3"
    fi
    $PYTHON_BIN -c "
    import yaml
    import os

    # Validate bundled mvp.yaml config
    try:
        with open('config/mvp.yaml', 'r') as f:
            config = yaml.safe_load(f)
        print('[OK] config/mvp.yaml syntax valid')
    except yaml.YAMLError as e:
        print(f'[FAIL] config/mvp.yaml syntax error: {e}')
        exit(1)
    except FileNotFoundError:
        print('[WARNING] config/mvp.yaml not found - using app defaults')

    # Check .env file
    if os.path.exists('.env'):
        print('[OK] .env file created')
    else:
        print('[WARNING] .env file not found')
    "
  register: config_validation
  changed_when: false

- name: Secure environment file permissions
  ansible.builtin.file:
    path: "{{ parking_monitor_repository.destination }}/.env"
    mode: "0600"
    owner: "{{ parking_monitor_service.user }}"
    group: "{{ parking_monitor_service.group }}"

- name: Configuration summary
  ansible.builtin.debug:
    msg: |
      [SVC]  Configuration Setup Complete:
      ===============================
      Main Config: {{ parking_monitor_repository.destination }}/config/mvp.yaml (bundled)
      Environment: {{ parking_monitor_repository.destination }}/.env
      Validation: {{ config_validation.stdout }}
      ==============================="
