---
# Simplified Parking Monitor Role - Device Setup Only
# Focuses on device preparation, repository setup, and service installation

- name: Include pre-deployment checks
  ansible.builtin.include_tasks:
    file: pre_checks.yml
    apply:
      tags: [parking-monitor, pre-checks]
  tags: [parking-monitor, pre-checks]


- name: Include repository setup
  ansible.builtin.include_tasks:
    file: repository_setup.yml
    apply:
      tags: [parking-monitor, repository]
  tags: [parking-monitor, repository]


- name: Include Python environment setup
  ansible.builtin.include_tasks:
    file: python_environment.yml
    apply:
      tags: [parking-monitor, python]
  tags: [parking-monitor, python]

- name: Include configuration setup
  ansible.builtin.include_tasks:
    file: configuration.yml
    apply:
      tags: [parking-monitor, configuration]
  tags: [parking-monitor, configuration]

- name: Include service setup (LaunchAgent)
  ansible.builtin.include_tasks:
    file: service_setup.yml
    apply:
      tags: [parking-monitor, service]
  tags: [parking-monitor, service]

- name: Include security configuration
  ansible.builtin.include_tasks:
    file: security_setup.yml
    apply:
      tags: [parking-monitor, security]
  tags: [parking-monitor, security]

- name: Include health verification
  ansible.builtin.include_tasks:
    file: health_verification.yml
    apply:
      tags: [parking-monitor, health, verify]
  tags: [parking-monitor, health, verify]


- name: Display deployment summary with standardized commit verification
  ansible.builtin.debug:
    msg: |
      ===============================================
      [SUCCESS] Parking Monitor Deployment Complete
      ===============================================
      Repository: {{ parking_monitor_repository.url }}
      Branch: {{ parking_monitor_repository.branch }}
      Destination: {{ parking_monitor_repository.destination }}
      Service: {{ parking_monitor_service.name }}
      Environment: {{ parking_monitor_environment.PARKING_MONITOR_ENV }}
      Python Setup: uv-managed virtual environment
      
      STANDARDIZED COMMIT VERIFICATION:
      {% if parking_monitor_repo_info is defined %}
      {% set info = parking_monitor_repo_info %}
      Current Commit: {{ info.final_commit[:8] if info.final_commit != 'unknown' else 'N/A' }}
      Branch: {{ info.final_branch }}
      Last Message: {{ info.final_message }}
      Author: {{ info.final_author }}
      Updated: {{ info.final_timestamp }}
      Repository Status: [{{ 'UPDATED' if info.updated else 'VERIFIED' }}]
      {% else %}
      Repository Status: [WARNING] Commit info not available
      {% endif %}
      ===============================================
      [SUCCESS] Device setup completed successfully!

      Project Configuration:
      - Configuration managed by project in config/ directory
      - Environment: {{ parking_monitor_environment.PARKING_MONITOR_ENV }}
      - Project will auto-configure based on environment
      - Code verified with standardized git management

      Next steps:
      1. Service will start automatically via LaunchAgent
      2. Check project logs: {{ parking_monitor_repository.destination }}/logs/
      3. Monitor via oaDashboard for health and metrics
      4. Force update: Use --force flag for all repositories
      ===============================================
  tags: [parking-monitor, summary]
