---
# Pre-deployment checks for parking monitor
# Ensures system meets requirements before attempting deployment

- name: Check macOS version compatibility
  ansible.builtin.assert:
    that:
      - ansible_distribution == "MacOSX"
      - ansible_distribution_version is version('12.0', '>=')
    fail_msg: "Parking Monitor requires macOS 12.0+ (Monterey) for M1 support"
    success_msg: "[OK] macOS version {{ ansible_distribution_version }} is compatible"

- name: Check hardware architecture
  ansible.builtin.assert:
    that:
      - ansible_architecture == "arm64"
    fail_msg: "Parking Monitor is optimized for Apple Silicon (M1/M2). Intel support not implemented."
    success_msg: "[OK] Apple Silicon ({{ ansible_architecture }}) detected"

- name: Check available memory
  ansible.builtin.assert:
    that:
      - ansible_memtotal_mb >= 8192 # 8GB minimum
    fail_msg: "Parking Monitor requires at least 8GB RAM. Found {{ ansible_memtotal_mb }}MB"
    success_msg: "[OK] Sufficient memory available: {{ ansible_memtotal_mb }}MB"

- name: Check UV installation and Python version availability
  ansible.builtin.shell: |
    set -e
    
    # Check if UV is available
    if command -v uv >/dev/null 2>&1; then
      # UV is available, check if it can provide Python {{ parking_monitor_python.version }}
      if uv python list | grep -q "{{ parking_monitor_python.version }}"; then
        echo "UV_PYTHON_OK={{ parking_monitor_python.version }}"
        exit 0
      elif uv python install {{ parking_monitor_python.version }} --quiet 2>/dev/null; then
        echo "UV_PYTHON_INSTALLED={{ parking_monitor_python.version }}"
        exit 0
      fi
    fi
    
    # Fallback: check system Python
    if command -v python{{ parking_monitor_python.version }} >/dev/null 2>&1; then
      PYTHON_VERSION=$(python{{ parking_monitor_python.version }} --version 2>&1)
      if echo "$PYTHON_VERSION" | grep -q "{{ parking_monitor_python.version }}"; then
        echo "SYSTEM_PYTHON_OK={{ parking_monitor_python.version }}"
        exit 0
      fi
    fi
    
    # No Python found
    echo "NO_PYTHON_FOUND"
    exit 1
  register: python_version_check
  failed_when: false
  changed_when: false

- name: Verify Python version availability
  ansible.builtin.assert:
    that:
      - python_version_check.rc == 0
      - python_version_check.stdout != "NO_PYTHON_FOUND"
    fail_msg: |
      Python {{ parking_monitor_python.version }} not available.
      Please ensure UV is installed or Python {{ parking_monitor_python.version }} is available system-wide.
      UV installation: curl -LsSf https://astral.sh/uv/install.sh | sh
    success_msg: "[OK] Python {{ parking_monitor_python.version }} available ({{ python_version_check.stdout }})"

- name: Check for existing conflicting services
  ansible.builtin.shell: |
    launchctl list | grep -E "(parking.monitor|alpr)" | wc -l
  register: conflicting_services
  changed_when: false

- name: Warn about conflicting services
  ansible.builtin.debug:
    msg: |
      [WARNING]  WARNING: Found {{ conflicting_services.stdout }} potentially conflicting services.
      This may indicate existing ALPR or parking monitor installations.
      Review with: launchctl list | grep -E "(parking.monitor|alpr)"
  when: conflicting_services.stdout | int > 0

- name: Check port availability
  ansible.builtin.wait_for:
    port: "{{ parking_monitor_service.port }}"
    state: stopped
    timeout: 1
  ignore_errors: true
  register: port_check

- name: Warn about port conflicts
  ansible.builtin.debug:
    msg: |
      [WARNING]  WARNING: Port {{ parking_monitor_service.port }} appears to be in use.
      This may cause deployment issues. Check with: lsof -i :{{ parking_monitor_service.port }}
  when: port_check is failed

- name: Check disk space
  ansible.builtin.shell: df -h "{{ ansible_user_dir }}" | tail -1 | awk '{print $4}' | sed 's/[iGMTB]//g'
  register: available_space
  changed_when: false

- name: Verify sufficient disk space
  ansible.builtin.assert:
    that:
      - available_space.stdout | float >= 5.0 # 5GB minimum
    fail_msg: "Insufficient disk space. Need 5GB, found {{ available_space.stdout }}GB available"
    success_msg: "[OK] Sufficient disk space: {{ available_space.stdout }}GB available"

- name: Check camera availability (optional)
  ansible.builtin.shell: |
    system_profiler SPCameraDataType | grep -q "Built-in" && echo "builtin" || echo "none"
  register: camera_check
  changed_when: false
  failed_when: false

- name: Report camera status
  ansible.builtin.debug:
    msg: |
      [CAMERA] Camera Status: {{ 'Built-in camera detected' if camera_check.stdout == 'builtin' else 'No built-in camera detected - ensure USB camera is connected' }}

- name: Check Git availability and GitHub access
  block:
    - name: Check Git installation
      ansible.builtin.command: git --version
      register: git_version
      changed_when: false

    - name: Test HTTPS access to GitHub repository
      ansible.builtin.command: git ls-remote --heads {{ parking_monitor_repository.url }}
      register: github_test
      changed_when: false
      failed_when: false
      timeout: 30

    - name: Verify GitHub repository access
      ansible.builtin.assert:
        that:
          - github_test.rc == 0
          - github_test.stdout | length > 0
        fail_msg: |
          HTTPS access to GitHub repository failed.
          Repository: {{ parking_monitor_repository.url }}
          Please ensure network connectivity and repository accessibility.
          Test with: git ls-remote --heads {{ parking_monitor_repository.url }}
        success_msg: "[OK] GitHub HTTPS repository access verified"

- name: Summary of pre-deployment checks
  ansible.builtin.debug:
    msg: |
      [VERIFY] Pre-deployment Check Summary:
      ================================
      [OK] macOS {{ ansible_distribution_version }} ({{ ansible_architecture }})
      [OK] Python {{ parking_monitor_python.version }}
      [OK] Memory: {{ ansible_memtotal_mb }}MB
      [OK] Disk: {{ available_space.stdout }}GB available
      [OK] Git: {{ git_version.stdout }}
      [OK] GitHub SSH access verified
      [CAMERA] Camera: {{ 'Built-in detected' if camera_check.stdout == 'builtin' else 'USB camera required' }}
      [WEB] Port {{ parking_monitor_service.port }}: {{ 'Available' if port_check is succeeded else 'In use (warning)' }}
      ================================
      Ready for deployment! [LAUNCH]
