---
# Python environment setup tasks using uv
# Creates and configures the Python environment using uv for parking monitor

- name: Check if uv is installed
  shell: |
    if command -v uv >/dev/null 2>&1; then
      echo "installed"
    else
      echo "not_found"
    fi
  register: uv_check
  changed_when: false

- name: Install uv if not present
  shell: |
    curl -LsSf https://astral.sh/uv/install.sh | sh
    source $HOME/.cargo/env
  when: uv_check.stdout == "not_found"
  register: uv_install

- name: Set uv path for session
  set_fact:
    uv_binary: "{{ ansible_user_dir }}/.cargo/bin/uv"
  when: uv_install is defined and uv_install.changed

- name: Set uv path for existing installation
  set_fact:
    uv_binary: "uv"
  when: uv_check.stdout == "installed"

- name: Initialize uv project and install dependencies
  shell: |
    cd "{{ parking_monitor_repository.destination }}"
    if [ -f "$HOME/.cargo/env" ]; then
      source $HOME/.cargo/env
    fi
    {{ uv_binary }} sync
  register: uv_sync
  environment:
    PATH: "{{ ansible_user_dir }}/.cargo/bin:{{ ansible_env.PATH }}"

- name: Verify critical imports with uv
  shell: |
    cd "{{ parking_monitor_repository.destination }}"
    if [ -f "$HOME/.cargo/env" ]; then
      source $HOME/.cargo/env
    fi
    {{ uv_binary }} run python -c "
    try:
        import ultralytics, torch, cv2, fastapi, uvicorn, pydantic
        print('[OK] All critical imports successful')
    except ImportError as e:
        print(f'[FAIL] Import error: {e}')
        exit(1)
    "
  register: import_test
  changed_when: false
  failed_when: import_test.rc != 0
  environment:
    PATH: "{{ ansible_user_dir }}/.cargo/bin:{{ ansible_env.PATH }}"

- name: Check PyTorch MPS availability
  shell: |
    cd "{{ parking_monitor_repository.destination }}"
    if [ -f "$HOME/.cargo/env" ]; then
      source $HOME/.cargo/env
    fi
    {{ uv_binary }} run python -c "
    import torch
    if torch.backends.mps.is_available():
        print('[OK] MPS (Metal Performance Shaders) available')
    else:
        print('[WARNING]  MPS not available - falling back to CPU')
    "
  register: mps_check
  changed_when: false
  environment:
    PATH: "{{ ansible_user_dir }}/.cargo/bin:{{ ansible_env.PATH }}"

- name: Get Python version from uv environment
  shell: |
    cd "{{ parking_monitor_repository.destination }}"
    if [ -f "$HOME/.cargo/env" ]; then
      source $HOME/.cargo/env
    fi
    {{ uv_binary }} run python --version
  register: python_version
  changed_when: false
  environment:
    PATH: "{{ ansible_user_dir }}/.cargo/bin:{{ ansible_env.PATH }}"

- name: Create Python environment activation script
  copy:
    dest: "{{ parking_monitor_repository.destination }}/activate_env.sh"
    mode: '0755'
    content: |
      #!/bin/bash
      # Python Environment Activation Script - Generated by Ansible
      echo "Activating parking monitor uv environment..."
      cd "{{ parking_monitor_repository.destination }}"
      if [ -f "$HOME/.cargo/env" ]; then
        source $HOME/.cargo/env
      fi
      export PATH="$HOME/.cargo/bin:$PATH"
      export PYTHONPATH="{{ parking_monitor_repository.destination }}/src:$PYTHONPATH"
      echo "[OK] uv Environment activated - ready for parking monitor development"
      echo "Use 'uv run python' to execute Python with the project environment"

- name: Python environment setup summary
  debug:
    msg: |
      [PYTHON] Python Environment Setup Complete (uv):
      =========================================
      Python Version: {{ python_version.stdout }}
      Package Manager: uv (modern Python package management)
      Project Path: {{ parking_monitor_repository.destination }}
      Critical Imports: {{ '[OK] Success' if import_test.rc == 0 else '[FAIL] Failed' }}
      MPS Acceleration: {{ mps_check.stdout }}
      Activation Script: {{ parking_monitor_repository.destination }}/activate_env.sh
      =========================================