---
# Repository setup tasks
# Handles cloning and updating the oaParkingMonitor repository

- name: Create orangead directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/orangead"
    state: directory
    mode: "0755"

- name: Check if repository already exists
  ansible.builtin.stat:
    path: "{{ parking_monitor_repository.destination }}"
  register: repo_exists

- name: Clone parking monitor repository
  ansible.builtin.git:
    repo: "{{ parking_monitor_repository.url }}"
    dest: "{{ parking_monitor_repository.destination }}"
    version: "{{ parking_monitor_repository.branch }}"
    force: "{{ parking_monitor_repository.force_update | default(false) }}"
    update: true
  register: repo_clone
  when: not repo_exists.stat.exists or parking_monitor_repository.force_update | default(false)

- name: Update existing repository
  ansible.builtin.git:
    repo: "{{ parking_monitor_repository.url }}"
    dest: "{{ parking_monitor_repository.destination }}"
    version: "{{ parking_monitor_repository.branch }}"
    update: true
  register: repo_update
  when: repo_exists.stat.exists and not parking_monitor_repository.force_update | default(false)

- name: Set repository permissions
  ansible.builtin.file:
    path: "{{ parking_monitor_repository.destination }}"
    owner: "{{ parking_monitor_service.user }}"
    group: "{{ parking_monitor_service.group }}"
    mode: "0755"
    recurse: true

- name: Make scripts executable
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
  with_fileglob:
    - "{{ parking_monitor_repository.destination }}/scripts/*"
  ignore_errors: true # Some files might not exist yet

- name: Create logs directory
  ansible.builtin.file:
    path: "{{ parking_monitor_repository.destination }}/logs"
    state: directory
    mode: "0755"

- name: Create models directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ parking_monitor_models.model_dir }}"
    - "{{ parking_monitor_models.downloads_dir }}"
    - "{{ parking_monitor_models.exports_dir }}"

- name: Repository setup summary
  ansible.builtin.debug:
    msg: |
      [PACKAGE] Repository Setup Complete:
      =============================
      Repository: {{ parking_monitor_repository.url }}
      Branch: {{ parking_monitor_repository.branch }}
      Location: {{ parking_monitor_repository.destination }}
      Status: {{ 'Cloned' if repo_clone is changed else ('Updated' if repo_update is changed else 'Already up-to-date') }}
      =============================
