---
# Repository setup tasks with standardized git management
# Uses the unified git-repository-management.yml for consistent behavior

- name: Setup parking monitor repository with standardized git management
  ansible.builtin.include_tasks: "{{ playbook_dir }}/../tasks/git-repository-management.yml"
  vars:
    repo_component_name: "parking_monitor"
    repo_url: "{{ parking_monitor_repository.url }}"
    repo_branch: "{{ parking_monitor_repository.branch }}"
    repo_destination: "{{ parking_monitor_repository.destination }}"
    repo_force_update: "{{ parking_monitor_force_update | default(false) }}"
    repo_owner: "{{ parking_monitor_service.user }}"
    repo_group: "{{ parking_monitor_service.group }}"
    repo_tags: [parking-monitor, repository]
  tags: [parking-monitor, repository]

- name: Find all shell scripts in scripts directory
  ansible.builtin.find:
    paths: "{{ parking_monitor_repository.destination }}/scripts"
    patterns: "*.sh"
  register: parking_monitor_scripts

- name: Make all shell scripts executable
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: "0755"
  loop: "{{ parking_monitor_scripts.files }}"
  tags: [parking-monitor, repository]

- name: Create logs directory
  ansible.builtin.file:
    path: "{{ parking_monitor_repository.destination }}/logs"
    state: directory
    mode: "0755"
  tags: [parking-monitor, repository]

- name: Create models directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ parking_monitor_models.model_dir }}"
    - "{{ parking_monitor_models.downloads_dir }}"
    - "{{ parking_monitor_models.exports_dir }}"
  tags: [parking-monitor, repository]