---
# Service setup tasks
# Creates and configures the LaunchAgent service for parking monitor

- name: Create LaunchAgents directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/Library/LaunchAgents"
    state: directory
    mode: "0755"

- name: Generate LaunchAgent plist
  ansible.builtin.template:
    src: com.orangead.parking-monitor.plist.j2
    dest: "{{ parking_monitor_launchd.plist_path }}"
    mode: "0644"
    backup: true
  notify: restart parking monitor

- name: Create scripts directory
  ansible.builtin.file:
    path: "{{ parking_monitor_repository.destination }}/scripts"
    state: directory
    mode: "0755"

- name: Create aliases script if missing
  ansible.builtin.copy:
    dest: "{{ parking_monitor_repository.destination }}/scripts/aliases.sh"
    mode: "0755"
    content: |
      #!/bin/bash
      # Native aliases for oaParkingMonitor service management
      
      # Service management aliases
      alias parking-start='./scripts/start.sh'
      alias parking-stop='./scripts/stop.sh' 
      alias parking-restart='./scripts/restart.sh'
      alias parking-status='./scripts/health_check.sh'
      alias parking-logs='./scripts/logs.sh'
      
      # Development aliases
      alias parking-setup='./scripts/setup.sh'
      alias parking-validate='./scripts/validate.sh'
      
      # Configuration aliases
      alias parking-config='nano config.yaml'
      alias parking-config-staging='cp config/staging.yaml config.yaml'
      alias parking-config-preprod='cp config/preprod.yaml config.yaml'
      
      # Monitoring aliases
      alias parking-health='curl -s http://localhost:9091/health | jq .'
      alias parking-stats='curl -s http://localhost:9091/api/stats | jq .'
      
      echo "Parking monitor aliases loaded."

- name: Verify native scripts are executable
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
  loop:
    - "{{ parking_monitor_repository.destination }}/scripts/start.sh"
    - "{{ parking_monitor_repository.destination }}/scripts/health_check.sh"
    - "{{ parking_monitor_repository.destination }}/scripts/setup.sh"
    - "{{ parking_monitor_repository.destination }}/scripts/aliases.sh"
  ignore_errors: true

- name: Stop existing service if running
  ansible.builtin.shell: |
    launchctl unload "{{ parking_monitor_launchd.plist_path }}" 2>/dev/null || true
  changed_when: false

- name: Load LaunchAgent service
  ansible.builtin.shell: |
    launchctl load "{{ parking_monitor_launchd.plist_path }}"
  register: service_load

- name: Wait for service to initialize
  ansible.builtin.pause:
    seconds: 10
    prompt: "Waiting for parking monitor service to initialize..."

- name: Check service status
  ansible.builtin.shell: |
    launchctl list | grep "{{ parking_monitor_service.name }}" || echo "not_running"
  register: service_status
  changed_when: false

- name: Verify service is loaded
  ansible.builtin.assert:
    that:
      - "'not_running' not in service_status.stdout"
    fail_msg: "Service failed to load. Check logs: tail -f {{ parking_monitor_launchd.standard_error_path }}"
    success_msg: "[OK] Service loaded successfully"

- name: Verify native alias script is executable
  ansible.builtin.file:
    path: "{{ parking_monitor_repository.destination }}/scripts/aliases.sh"
    mode: "0755"
  ignore_errors: true

- name: Service setup summary
  ansible.builtin.debug:
    msg: |
      [LAUNCH] Service Setup Complete:
      =========================
      Service Name: {{ parking_monitor_service.name }}
      LaunchAgent: {{ parking_monitor_launchd.plist_path }}
      Status: {{ 'Running' if 'not_running' not in service_status.stdout else 'Failed to start' }}
      Environment: {{ parking_monitor_environment.PARKING_MONITOR_ENV }}

      Management Commands:
      • Start:   launchctl load {{ parking_monitor_launchd.plist_path }}
      • Stop:    launchctl unload {{ parking_monitor_launchd.plist_path }}
      • Status:  launchctl list | grep {{ parking_monitor_service.name }}
      • Health:  {{ parking_monitor_repository.destination }}/scripts/health_check.sh
      • Setup:   {{ parking_monitor_repository.destination }}/scripts/setup.sh
      • Native:  {{ parking_monitor_repository.destination }}/scripts/start.sh
      • Logs:    tail -f {{ parking_monitor_launchd.standard_out_path }}
      ========================="
