---
# MediaMTX Demo Test Environment
# Purpose: Simple MediaMTX demo with auto-start and Python camera reading
# Machine: f1-ca-001 (kampus machine) - deploys to ~/mediamtx-demo
# Requirements: Load on boot, stay open, basic Python camera example

all:
  vars:
    # Environment identification
    target_env: "mediamtx-demo-test"
    oa_environment:
      name: "mediamtx-demo-test"
      stage: "test"
      description: "Simple MediaMTX demo environment"

  children:
    # Simplified structure for demo deployment
    macos:
      children:
        test:
          children:
            mediamtx_demo:
              children:
                demo_hosts:
                  hosts:
                    kampus-demo-001:
                      # f1-ca-001 hardware used for MediaMTX demo
                      ansible_host: 100.103.229.95
                      ansible_user: studio
                      ansible_port: 22
                      # Note: No become_password needed - running as user, not root
                      
                      # Demo-specific configuration  
                      demo_description: "Simple MediaMTX Demo with Auto-start"
                      demo_purpose: "Auto-start streaming with Python camera reading example"
                      
                      # Camera configuration for demo
                      cam_id: "57b4b3f6-bcb0-42f6-a60e-e7b1e88b7fca"